import { GoogleGenAI } from "@google/genai";


if (!process.env.GEMINI_API_KEY) {
    throw new Error(
        "GEMINI_API_KEY is not configured"
    );
}


const ai = new GoogleGenAI({
    apiKey: process.env.GEMINI_API_KEY
});


const SYSTEM_PROMPT = `
You are an expert software dependency upgrade analyzer.

You analyze evidence produced by a deterministic
repository and package analysis system.

Your job is to reason about whether changing a dependency
will actually affect the repository.

IMPORTANT RULES:

1. Static analysis is the source of truth for repository usage.

2. Do not invent API usage.

3. Do not invent API changes.

4. Only reason from the supplied evidence.

5. A major version does not automatically mean breaking.

6. A patch or minor version does not automatically mean safe.

7. If a removed API is actually used by the repository,
   classify it as a "confirmed breaking change".

8. A changed API signature must be evaluated against the
   actual repository call site and compatibility evidence.

9. Consider the actual number and nature of arguments passed
   by the repository.

10. Consider removed parameters.

11. Consider newly required parameters.

12. Consider changed parameter types when evidence is available.

13. Consider changed return types when evidence is available.

14. Added APIs normally do not break existing repository code.

15. Release notes and documentation are supporting evidence.
    They are not a replacement for static analysis.

16. Do not claim that an API affects the repository unless
    the supplied evidence shows repository usage.

17. Do not invent file names or line numbers.

18. Do not invent migration APIs or replacement APIs.

19. Migration instructions must be supported by deterministic
    analysis or documentation evidence.

20. If the supplied evidence is insufficient to determine
    compatibility or migration, explicitly classify it as
    "insufficient evidence".

21. Use "likely breaking change" only when the supplied evidence
    strongly suggests a break but deterministic compatibility
    analysis does not conclusively prove it.

22. Use "documentation-only change" when documentation describes
    a change but there is no demonstrated repository impact.

23. Use "no impact" when the changed API does not affect the
    repository usage shown in the evidence.

24. Prefer exact repository file and line references.

25. Do not make recommendations unrelated to the detected change.

26. Keep confidence proportional to the quality of the evidence.

27. Return ONLY valid JSON.
`;


function cleanJsonResponse(text) {

    if (!text) {
        throw new Error(
            "Gemini returned an empty response"
        );
    }


    let cleaned = text.trim();


    /*
     * Gemini can sometimes return:
     *
     * ```json
     * {...}
     * ```
     *
     * Remove the markdown wrapper.
     */

    if (cleaned.startsWith("```")) {

        cleaned = cleaned
            .replace(
                /^```json\s*/i,
                ""
            )
            .replace(
                /^```\s*/i,
                ""
            )
            .replace(
                /\s*```$/i,
                ""
            )
            .trim();
    }


    return cleaned;
}


function buildUserPrompt(evidence) {

    return `
Analyze the following dependency upgrade.

The evidence was generated by deterministic
static analysis and package analysis.

Do not assume anything that is not present
in the evidence.

==================================================
DEPENDENCY UPGRADE
==================================================

Package:
${evidence.package}

Project:
${evidence.project}

Current version:
${evidence.from}

Target version:
${evidence.to}


==================================================
API CHANGES
==================================================

${JSON.stringify(
    evidence.apiChanges || {},
    null,
    2
)}


==================================================
REPOSITORY IMPACTS
==================================================

These are the repository usages that deterministic
analysis identified as potentially affected.

${JSON.stringify(
    evidence.impacts || [],
    null,
    2
)}


==================================================
COMPATIBILITY ANALYSIS
==================================================

This contains deterministic analysis of the actual
repository call sites against the target API.

Treat this as strong evidence.

${JSON.stringify(
    evidence.compatibility || [],
    null,
    2
)}


==================================================
DOCUMENTATION EVIDENCE
==================================================

This evidence comes from package documentation,
README, changelog, or other retrieved package
knowledge.

Use it to explain why an API changed and how
developers should migrate when the documentation
actually supports that conclusion.

Do not invent migration instructions when the
documentation does not provide them.

${JSON.stringify(
    evidence.documentationEvidence || [],
    null,
    2
)}


==================================================
RELEASE NOTES
==================================================

${JSON.stringify(
    evidence.releaseNotes || [],
    null,
    2
)}


==================================================
PACKAGE METADATA
==================================================

${JSON.stringify(
    evidence.packageMetadata || {},
    null,
    2
)}


==================================================
REPOSITORY FILES
==================================================

These are repository files associated with the
detected impacts.

${JSON.stringify(
    evidence.repositoryFiles || [],
    null,
    2
)}


==================================================
REASONING INSTRUCTIONS
==================================================

For every affected API:

1. Inspect the old API.

2. Inspect the new API.

3. Inspect the repository usage.

4. Inspect the actual call site when available.

5. Inspect argument count when available.

6. Inspect parameter changes.

7. Inspect compatibility analysis.

8. Use documentation evidence to explain the change
   when relevant.

9. Determine whether the repository's actual usage
   conflicts with the target API.

IMPORTANT:

If an API is removed and the repository uses it:

    classification = "confirmed breaking change"

If deterministic compatibility analysis proves that
the repository call is incompatible:

    classification = "confirmed breaking change"

If the evidence strongly suggests a break but does
not conclusively prove it:

    classification = "likely breaking change"

If documentation describes a change but the supplied
repository evidence does not demonstrate an impact:

    classification = "documentation-only change"

If the changed API does not affect the repository usage:

    classification = "no impact"

If there is not enough evidence to determine the result:

    classification = "insufficient evidence"


==================================================
MIGRATION RULES
==================================================

Only provide migration steps when they are supported
by:

- deterministic API analysis
- deterministic compatibility analysis
- package documentation
- release notes

Never invent a replacement API.

If documentation says to replace an API with another
API, you may recommend that replacement.

If no supported migration path is available, explain
that additional documentation or manual investigation
is required.


==================================================
OUTPUT
==================================================

Return exactly one JSON object with this structure:

{
    "overallRisk": "low | medium | high",

    "breaking": true,

    "confidence": 0.0,

    "summary": "Short explanation of the overall upgrade impact",

    "impacts": [
        {
            "api": "API name",

            "file": "repository file",

            "line": 0,

            "severity": "low | medium | high",

            "classification":
                "confirmed breaking change"
                | "likely breaking change"
                | "documentation-only change"
                | "no impact"
                | "insufficient evidence",

            "reason": "Why this usage is or is not affected",

            "migrationSteps": [
                "Supported migration step"
            ],

            "confidence": 0.0
        }
    ],

    "migrationSteps": [
        "Supported migration step"
    ],

    "additionalNotes": [
        "Important caveat or limitation"
    ]
}


OUTPUT RULES:

- Return valid JSON only.
- Do not use markdown.
- Do not include code fences.
- Do not include explanations outside the JSON.
- Do not invent missing information.
- Use an empty array when there are no migration steps.
- Use an empty array when there are no additional notes.
- Use the exact file and line information supplied by
  deterministic analysis.
- Do not change repository file names or line numbers.
`;
}


async function analyzeUpgradeWithLLM(
    evidence
) {

    if (!evidence) {
        throw new Error(
            "LLM evidence is required"
        );
    }


    const userPrompt =
        buildUserPrompt(evidence);


    console.log(
        "Sending evidence to Gemini..."
    );


    const response =
        await ai.models.generateContent({

            model:
                "gemini-3.5-flash",

            contents: [
                {
                    role: "user",
                    parts: [
                        {
                            text:
                                `${SYSTEM_PROMPT}\n\n${userPrompt}`
                        }
                    ]
                }
            ],

            config: {
                temperature: 0.1
            }
        });


    const output =
        response.text;


    const jsonText =
        cleanJsonResponse(
            output
        );


    try {

        return JSON.parse(
            jsonText
        );

    } catch {

        console.error(
            "Gemini raw response:"
        );

        console.error(
            output
        );

        throw new Error(
            "Gemini returned invalid JSON"
        );
    }
}


export {
    analyzeUpgradeWithLLM
};